#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from md_truth_inventory_lib import (
    PUBLIC_GENERATOR_CMD,
    ROOT,
    build_inventory,
    deprecation_rows,
    find_orphans,
    staleness_rows,
    summary_counts,
    task_surface_rows,
)


GENERATED_DIR = ROOT / "docs/generated"
INVENTORY_MD = GENERATED_DIR / "md_inventory.md"
INVENTORY_JSON = GENERATED_DIR / "md_inventory.json"
ORPHANS_MD = GENERATED_DIR / "md_orphans.md"
DEPRECATION_MD = GENERATED_DIR / "md_deprecation_matrix.md"
CLEANUP_MD = GENERATED_DIR / "md_cleanup_report.md"
STALENESS_MD = GENERATED_DIR / "md_staleness_report.md"
TASK_SURFACE_MD = GENERATED_DIR / "task_surface_matrix.md"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def _generated_header(title: str) -> list[str]:
    return [
        title,
        "",
        f"Generated by `{PUBLIC_GENERATOR_CMD}`.",
        "",
    ]


def _render_inventory_md(inventory: list[dict]) -> str:
    lines = _generated_header("# Markdown Inventory")
    lines.extend(
        [
            "| Path | Classification | Owner | Replacement | Action | Actionable | Indexed | Review | Enforced | Auth Lang | Run IDs | `/home` |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in inventory:
        lines.append(
            "| `{path}` | `{classification}` | `{owner_surface}` | `{canonical_replacement}` | `{action}` | `{actionable_status}` | `{indexed_from_canonical_entrypoint}` | `{review_status}` | `{review_enforced}` | `{contains_authoritative_language}` | `{contains_run_ids}` | `{contains_machine_local_paths}` |".format(
                **row
            )
        )
    return "\n".join(lines)


def _render_orphans_md(orphans: list[dict]) -> str:
    lines = _generated_header("# Markdown Orphans")
    if not orphans:
        lines.append("No orphan control-plane Markdown surfaces detected.")
        return "\n".join(lines)
    lines.extend(
        [
            "| Path | Owner | Action | Reason |",
            "| --- | --- | --- | --- |",
        ]
    )
    for row in orphans:
        lines.append(f"| `{row['path']}` | `{row['owner_surface']}` | `{row['action']}` | {row['reason']} |")
    return "\n".join(lines)


def _render_deprecation_md(rows: list[dict]) -> str:
    lines = _generated_header("# Markdown Deprecation Matrix")
    lines.extend(
        [
            "| Path | Classification | Replacement | Action | Reason |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for row in rows:
        lines.append(
            f"| `{row['path']}` | `{row['classification']}` | `{row['canonical_replacement']}` | `{row['action']}` | {row['reason']} |"
        )
    return "\n".join(lines)


def _render_cleanup_md(inventory: list[dict], orphans: list[dict], deprecations: list[dict]) -> str:
    counts = summary_counts(inventory)
    lines = _generated_header("# Markdown Cleanup Report")
    lines.extend(["## Classification Counts", ""])
    for key in sorted(counts):
        lines.append(f"- `{key}`: {counts[key]}")
    lines.extend(
        [
            "",
            "## Key Decisions",
            "",
            "- `results_meta/` remains the canonical committed authority for current/promoted result meaning.",
            "- `docs/bridge/current_status.md` is expected to stay a dashboard, not a result ledger.",
            "- `tasks/spec/`, `tasks/implement/`, `tasks/status/`, and `plans/active/` are active-only neighborhoods; historical execution artifacts belong under `tasks/history/` and `plans/completed/`.",
            "- `python scripts/generate_md_inventory.py` is the only public inventory-regeneration command.",
            "",
            "## Surfaces Requiring Action",
            "",
        ]
    )
    action_rows = [row for row in inventory if row["actionable_status"] == "actionable"]
    if not action_rows:
        lines.append("- No non-trivial cleanup actions are currently outstanding in the inventory snapshot.")
    else:
        for row in action_rows:
            lines.append(f"- `{row['path']}` -> `{row['action']}`: {row['reason']}")
    lines.extend(
        [
            "",
            "## Deprecation / Historical Summary",
            "",
            f"- deprecated/historical/local-only surfaces tracked: `{len(deprecations)}`.",
            f"- orphan surfaces tracked: `{len(orphans)}`.",
            "",
            "## Workflow Usage Status",
            "",
            "- `planner-spec`: partially load-bearing through the repo-native task/spec/plan chain, but not directly auditable per task.",
            "- `milestone-contract` / `tasks/contracts/`: selectively load-bearing only when real contract files exist under `tasks/contracts/`.",
            "- `handoff-resume` / `tasks/handoffs/`: selectively load-bearing only when real handoff files exist under `tasks/handoffs/`.",
            "- `skeptical-video-audit`: partially load-bearing; scripts and hooks exist, but task closeout still needs explicit verdict-surface discipline.",
        ]
    )
    return "\n".join(lines)


def _render_staleness_md(rows: list[dict]) -> str:
    lines = _generated_header("# Markdown Staleness Report")
    if not rows:
        lines.append("No review-age, overgrowth, or line-compression issues detected in the current inventory snapshot.")
        return "\n".join(lines)
    lines.extend(
        [
            "This report is intentionally narrowed to the enforced high-signal review scope plus any surface that is overgrown or line-compressed.",
            "It is meant to function as a maintenance queue, not a permanent wall of red template files.",
            "",
        ]
    )
    lines.extend(
        [
            "| Path | Classification | Review | Age (d) | Interval (d) | Enforced | Overgrown | Compressed | Action |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in rows:
        lines.append(
            "| `{path}` | `{classification}` | `{review_status}` | `{review_age_days}` | `{review_interval_days}` | `{review_enforced}` | `{overgrown_for_role}` | `{line_compressed}` | `{action}` |".format(
                **row
            )
        )
    return "\n".join(lines)


def _render_task_surface_md(rows: list[dict]) -> str:
    lines = _generated_header("# Task Surface Matrix")
    lines.extend(
        [
            "This matrix shows whether each active task has a full chain, registry backing, and real contract/handoff artifacts.",
            "Template files alone do not count as workflow usage.",
            "",
        ]
    )
    lines.extend(
        [
            "| Task | Task Page | Spec | Plan | Implement | Status | Contract | Handoff | Registry | Registry State | Current Run |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in rows:
        lines.append(
            "| `{task_slug}` | `{task_page}` | `{spec}` | `{plan}` | `{implement}` | `{status}` | `{contract}` | `{handoff}` | `{registry_backed}` | `{registry_state}` | `{registry_run_id}` |".format(
                **row
            )
        )
        if row["contract_paths"] or row["handoff_paths"]:
            lines.append(
                f"|  |  |  |  |  |  | `{row['contract_paths'] or '-'}` | `{row['handoff_paths'] or '-'}` |  |  |  |"
            )
    return "\n".join(lines)


def main() -> int:
    inventory = build_inventory()
    orphans = find_orphans(inventory)
    deprecations = deprecation_rows(inventory)
    stale = staleness_rows(inventory)
    task_rows = task_surface_rows()

    INVENTORY_JSON.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _write(INVENTORY_MD, _render_inventory_md(inventory))
    _write(ORPHANS_MD, _render_orphans_md(orphans))
    _write(DEPRECATION_MD, _render_deprecation_md(deprecations))
    _write(CLEANUP_MD, _render_cleanup_md(inventory, orphans, deprecations))
    _write(STALENESS_MD, _render_staleness_md(stale))
    _write(TASK_SURFACE_MD, _render_task_surface_md(task_rows))

    for path in (
        INVENTORY_JSON,
        INVENTORY_MD,
        ORPHANS_MD,
        DEPRECATION_MD,
        CLEANUP_MD,
        STALENESS_MD,
        TASK_SURFACE_MD,
    ):
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
