#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from md_truth_inventory_lib import ROOT, build_inventory, deprecation_rows, find_orphans, summary_counts


GENERATED_DIR = ROOT / "docs/generated"
INVENTORY_MD = GENERATED_DIR / "md_inventory.md"
INVENTORY_JSON = GENERATED_DIR / "md_inventory.json"
ORPHANS_MD = GENERATED_DIR / "md_orphans.md"
DEPRECATION_MD = GENERATED_DIR / "md_deprecation_matrix.md"
CLEANUP_MD = GENERATED_DIR / "md_cleanup_report.md"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def _render_inventory_md(inventory: list[dict]) -> str:
    lines = [
        "# Markdown Inventory",
        "",
        "Generated by `python scripts/generate_md_truth_inventory.py`.",
        "",
        "| Path | Classification | Owner | Replacement | Action | Auth Lang | Run IDs | `/home` |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in inventory:
        lines.append(
            "| `{path}` | `{classification}` | `{owner_surface}` | `{canonical_replacement}` | `{action}` | `{contains_authoritative_language}` | `{contains_run_ids}` | `{contains_machine_local_paths}` |".format(
                **row
            )
        )
    return "\n".join(lines)


def _render_orphans_md(orphans: list[dict]) -> str:
    lines = [
        "# Markdown Orphans",
        "",
        "Generated by `python scripts/generate_md_truth_inventory.py`.",
        "",
    ]
    if not orphans:
        lines.append("No orphan canonical control-plane Markdown surfaces detected.")
        return "\n".join(lines)
    lines.extend(
        [
            "| Path | Owner | Reason |",
            "| --- | --- | --- |",
        ]
    )
    for row in orphans:
        lines.append(f"| `{row['path']}` | `{row['owner_surface']}` | {row['reason']} |")
    return "\n".join(lines)


def _render_deprecation_md(rows: list[dict]) -> str:
    lines = [
        "# Markdown Deprecation Matrix",
        "",
        "Generated by `python scripts/generate_md_truth_inventory.py`.",
        "",
        "| Path | Classification | Replacement | Action | Reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| `{row['path']}` | `{row['classification']}` | `{row['canonical_replacement']}` | `{row['action']}` | {row['reason']} |"
        )
    return "\n".join(lines)


def _render_cleanup_md(inventory: list[dict], orphans: list[dict], deprecations: list[dict]) -> str:
    counts = summary_counts(inventory)
    tracked_secondary = [
        row["path"]
        for row in inventory
        if row["classification"] == "deprecated-pointer"
        and (
            row["path"].startswith("results/")
            or row["path"] == "Newton/phystwin_bridge/STATUS.md"
        )
    ]
    lines = [
        "# Markdown Cleanup Report",
        "",
        "Generated by `python scripts/generate_md_truth_inventory.py`.",
        "",
        "## Classification Counts",
        "",
    ]
    for key in sorted(counts):
        lines.append(f"- `{key}`: {counts[key]}")
    lines.extend(
        [
            "",
            "## Key Checks",
            "",
            "- Root singleton docs `Plan.md`, `Prompt.md`, `Status.md`, and `DecisionLog.md` are absent from the current filesystem.",
            "- `results_meta/` remains the canonical committed authority for run meaning.",
            "- Selected secondary/local-only Markdown pointer surfaces are explicitly inventoried instead of living outside the doc-control audit.",
            "- Deprecated and historical task families are expected to carry explicit metadata blocks and canonical replacements.",
            f"- Orphan canonical surfaces detected: `{len(orphans)}`.",
            "",
            "## Secondary Surfaces Under Control",
            "",
            f"- tracked deprecated/local-only pointer surfaces: `{len(tracked_secondary)}`.",
        ]
    )
    for rel in tracked_secondary:
        lines.append(f"  - `{rel}`")
    lines.extend(
        [
            "",
            "## Deprecated / Historical Surfaces",
            "",
            f"- Total deprecated/historical surfaces in the inventory: `{len(deprecations)}`.",
            "- See `md_deprecation_matrix.md` for the exact path-by-path mapping.",
            "",
            "## Machine-Local Path Risk",
            "",
            "- Canonical control-plane Markdown should not contain machine-local home-directory absolute paths.",
            "- Local convenience pointer files may still exist outside the canonical control plane, but they must not be treated as committed authority.",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    inventory = build_inventory()
    orphans = find_orphans(inventory)
    deprecations = deprecation_rows(inventory)

    INVENTORY_JSON.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _write(INVENTORY_MD, _render_inventory_md(inventory))
    _write(ORPHANS_MD, _render_orphans_md(orphans))
    _write(DEPRECATION_MD, _render_deprecation_md(deprecations))
    _write(CLEANUP_MD, _render_cleanup_md(inventory, orphans, deprecations))

    print(f"Wrote {INVENTORY_JSON.relative_to(ROOT)}")
    print(f"Wrote {INVENTORY_MD.relative_to(ROOT)}")
    print(f"Wrote {ORPHANS_MD.relative_to(ROOT)}")
    print(f"Wrote {DEPRECATION_MD.relative_to(ROOT)}")
    print(f"Wrote {CLEANUP_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
